### PR TITLE
Removed some settings. There are too many to maintain and some are old

### PR DESCRIPTION
**Pull request by AbuBaniaz**
I spoke to Captain before doing this

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
You only spoke with ATV???? All teams are involved in this. Most of these settings are quite popular.
I maintained the settings for the last couple of years, and none of them is 'old'.

**Comment by AbuBaniaz** [comment]
I only have contact details for Captain and other Vix members were fine.

Thanks for updating the settings even though they are not old. Two months is a long time for channel lists.

**Comment by RobvanderDoes** [comment]
Then maybe update them next time instead of deleting them?
My enthusiasm for updating settings has vanished since ATV insisted on using wrong satellite positions. I have no idea why we gave leeway for such an alien behaviour.

**Comment by RobvanderDoes** [comment]
Anyway: I'll delete a number of settings shortly, especially the combined SAT-DTT versions.

**Pull request closed without merging**
