### PR TITLE
Added some new settings lists

### PR DESCRIPTION
**Pull request by neoatomic**

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
1- Settings on feeds should not contain satellites.xml
2- Are you prepared to maintain those settings?

**Comment by neoatomic** [comment]
Will see if i can update them from time to time.

**Comment by AbuBaniaz** [comment]
Owing to the content of the iptv bouquets, is it a good idea having these available on the plugins server?

**Comment by RobvanderDoes** [comment]
> Owing to the content of the iptv bouquets, is it a good idea having these available on the plugins server?

I was very much doubting that; hence my reluctance to merge this request. After all there are plenty of options to add IPTV-services. On the other hand: we do already have settings on the feeds that (also) contain IPTV-streams.
And on top of that the 

> Will see if I can update them from time to time.
> 
> wasn't very reassuring either.

**Comment by neoatomic** [comment]
Indeed, other settings lists also have iptv bouquets, so i dont see a problem. And its not like those bouquets are for pay-TV channels. If you would follow that logic you can remove every Picon also. 
Leave alone some `plugins` on the feed...

Ciefp settings are one of the best lists out there, so not having them on the Repo would be a real shame.

But with `wasn't very reassuring either.` i dont feel comfortable to contribute anyway...

@atvcaptain

**Comment by atvcaptain** [comment]
@neoatomic , wir können das sonst in extra git packen wie bei giga, ich hab da keine Probleme mit und bauen es halt atv only ein

**Comment by RobvanderDoes** [comment]
Let's see if the settings will be updated regularly.

**Comment by neoatomic** [comment]
So after i just stated that i wasn't interested in contributing here anymore, you merge the PR and than state `Let's see if the settings will be updated regularly.` ???

I simply dont see what you are going on about to begin with. Even if a list isn't maintained than just remove it like you do with every redundant code. But as i stated before, i will pop-in an update from time to time for those lists.

@atvcaptain Danke fur das angebot. Das alles ist etwas kindisch, aber werde mal sehn wie er hier lauft. Is fur die community besser.

**Comment by RobvanderDoes** [comment]
I think there must be some language related misunderstanding. Feeds need to be maintained, otherwise they are meaningless. On my question to you if you would do so, you answered that this might be the case; hence my reluctance to merge.
In the end I did, in good faith for your future contributions, and now you complain about that? No idea what you're up to, but as I said: we'll see how it goes. 

BTW: You didn't say "_I will pop-in an update from time to time for those lists_" as you say now; you stated "_Will see if I can update them from time to time_", which is quite different.
Time will tell I guess.

**Comment by neoatomic** [comment]
There won't be any future contrib s from me anymore. I'm done here. 
You can revert the PR.

**Comment by RobvanderDoes** [comment]
Thanks, but no thanks. and also thanks for all the extra work on my part :-1: 
I really have no idea why you have this attitude, but I advise you to show it elsewhere.

**Pull request merged**
